spring:
  profiles:
    default: dev # ?? ???? dev / ??? prod


#### ?? ?? ?? ####
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000


jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 15
  refresh-token-expiration-minutes: 420
cloud:
  aws:
    credentials:
      secret-key: 1234
      access-key: 1234
    s3:
      bucket: togedog-image
    region:
      static: ap-northeast-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
