spring:
  profiles:
    default: prod # ?? ???? dev / ??? prod

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379


#### ?? ?? ?? ####
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 2000
          timeout: 2000
          writetimeout: 2000
          auth-code-expiration-millis: 1800000

jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 120
  refresh-token-expiration-minutes: 420


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

cloud:
  aws:
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
    s3:
      bucket: ${BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false
